name: Quality
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/master'
        uses: styfle/cancel-workflow-action@0.8.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: "/node_modules"
          key: node-${{ hashFiles('yarn.lock') }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Node Modules
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Formatting
        if: always()
        run: yarn format:check

      - name: Find old files
        uses: khorne3/action-find-old-files@master
        id: old_files
        with:
          minAge: 14
          dirs: '["admin", "cli", "environments", "guides", "images", "setup"]'

      - name: Save file
        uses: actions/upload-artifact@v2
        with:
          name: old-docs
          path: ${{ steps.old_files.outputs.files }}
